
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.practica1.Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIPOS = 22;
  public static final int LLAVE_ABRE = 16;
  public static final int MULTIPLICACION = 12;
  public static final int DOSPUNTOS = 27;
  public static final int LLAVE_CIERRA = 17;
  public static final int CORCHETE_CIERRA = 20;
  public static final int DEFINIR = 8;
  public static final int CORCHETE_ABRE = 19;
  public static final int DIVISION = 11;
  public static final int SUMA = 9;
  public static final int EJECUTAR = 6;
  public static final int ETIQUETA = 28;
  public static final int TIPO = 7;
  public static final int VALORES = 26;
  public static final int BARRAS = 4;
  public static final int COMA = 18;
  public static final int TOTAL = 29;
  public static final int EOF = 0;
  public static final int PIE = 5;
  public static final int EXTRA = 30;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 3;
  public static final int EJEY = 24;
  public static final int EJEX = 23;
  public static final int ENTERO = 2;
  public static final int ESPACIO = 31;
  public static final int UNIR = 25;
  public static final int TITULO = 21;
  public static final int PARENTESISB = 14;
  public static final int PARENTESISA = 13;
  public static final int RESTA = 10;
  public static final int PTCOMA = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "IDENTIFICADOR",
  "BARRAS",
  "PIE",
  "EJECUTAR",
  "TIPO",
  "DEFINIR",
  "SUMA",
  "RESTA",
  "DIVISION",
  "MULTIPLICACION",
  "PARENTESISA",
  "PARENTESISB",
  "PTCOMA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "COMA",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "TITULO",
  "TIPOS",
  "EJEX",
  "EJEY",
  "UNIR",
  "VALORES",
  "DOSPUNTOS",
  "ETIQUETA",
  "TOTAL",
  "EXTRA",
  "ESPACIO"
  };
}

